version: 2.1

orbs:

workflows:
  test-and-deploy:
    jobs:
      - set-data:
          context: heycar
      - read-data:
          context: heycar
          requires:
            - set-data      
   
definitions:
  node_image: &node-image
    docker:
      - image: cimg/node:14.15.5

executors:
  base-12-14-0:
    description: |
      Single Docker container with Node 12.14.0 and Cypress dependencies
      see https://github.com/cypress-io/cypress-docker-images/tree/master/base.
      Use example: `executor: cypress/base-12-14-0`.
    docker:
      - image: cypress/base:12.14.0

jobs:
  set-data:
    <<: *node-image
    description: Sets the data
    steps:
      - run: echo "AFFECTED_APPS=webapp" > global-vars
      - persist_to_workspace: 
          root: .
          paths:
            - global-vars
  read-data: 
    <<: *node-image
    description: read the data
    steps:   
      - attach_workspace: 
          at: .
      - run: ls 
      - run: cat global-vars
      - run: cat global-vars >> $BASH_ENV
      - run: echo "Test $AFFECTED_APPS"
      - when: 
          condition: 
            matches: {
              pattern: "webapp",
              value: $AFFECTED_APPS
            }
          steps:
            - run: echo "Tested"
